// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkaeicexpmvvlbwvzvdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrYWVpY2V4cG12dmxid3Z6dmR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODcyOTQsImV4cCI6MjA1ODY2MzI5NH0.TUBjG6RldSCZ1kBwlV35LXoX3lbd2WEjAifOEFD61sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);